const express = require('express')
const app = express()
const cors = require('cors')
app.use(cors())
require('./config/mongoose.config')
app.use(express.json(), express.urlencoded({extended: true}))
const productRoutes = require('./routes/product.routes')

productRoutes(app)
app.listen(8000, () => console.log("Server is connected on port 8000"))